[workspace]
resolver = "2"
members = [
    "contentauth-c2pa-builder",
    "contentauth-c2pa-file-builder",
    "contentauth-c2pa-file-reader",
    "contentauth-c2pa-format",
    "contentauth-c2pa-format-jpeg",
    "contentauth-c2pa-js-compat",
    "contentauth-c2pa-primitives",
    "contentauth-c2pa-reader",
    "contentauth-c2pa-rs-compat",
    "contentauth-state-machine",
]

[workspace.package]
authors = ["Eric Scouten <scouten@adobe.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/scouten-adobe/contentauth-state-machine"
rust-version = "1.88.0"
