codecov:
  notify:
    # Update this depending on how many independent jobs upload coverage results:
    # the workspace `tests` job, the `node-addon` and `node-sign-addon`
    # jobs, and the `cpp-binding` coverage job.
    # https://docs.codecov.com/docs/notifications#section-preventing-notifications-until-after-n-builds
    after_n_builds: 4

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
