
#### Description
This assertion is used to indicate one or more locations where a copy of the asset may be obtained.  Such locations shall each be described using an asset reference assertion. The location shall be expressed via a URI.  The URI may be to either a single asset or it may reference a directory. In the latter case, it serves to provide the location for a collection of assets, that would be hashed via a xref:_collection_data_hash[collection data hash]. 

NOTE: Expressing a `uri` provides flexibility to source the asset from web locations or distributed filesystems such as IPFS (see https://docs.ipfs.tech/how-to/address-ipfs-on-web/#subdomain-gateway[] for the latter).

An asset reference assertion shall have a label of `c2pa.asset-ref`.

The time-stamp within the assertion metadata provides a basis for determining the freshness of the link described as the reference.


#### Schema and Example

The schema for this type is defined by the `asset-ref-map` rule in the following {cddl}:

[source,cddl]
----
include::../schemas/cddl/asset-ref.cddl[]
----

An example in CBOR diagnostic notation ({8949}, clause 8) is shown below:

[source]
----
include::../examples/cbordiag/asset-ref.cbordiag[]
----
