:revdate: {docdate}
:version-label!:
:sectnums:
:sectnumlevels: 5
:chapter-label: Introduction
:source-highlighter: rouge

## Introduction

### Overview

With the increasing velocity of digital content and the increasing availability of powerful creation and editing techniques, establishing the provenance of media is critical to ensure transparency, understanding, and ultimately, trust.

We are witnessing extraordinary challenges to trust in media. As social platforms amplify the reach and influence of certain content via ever more complex and opaque algorithms, mis-attributed and mis-contextualized content spreads quickly. Whether inadvertent misinformation or deliberate deception via disinformation, inauthentic content is on the rise.

Currently, those who wish to include metadata about their work cannot do so in a secure, tamper-evident and standardized way across platforms. Without this information coming from a recognized source, publishers and consumers lack critical context for determining the authenticity of media.

Provenance empowers content creators and editors, regardless of their geographic location or degree of access to technology, to disclose information about how an asset was created, how it was changed and what was changed. Each time an asset is changed, the existing provenance of the asset is preserved, with each new change being added to the provenance. In this way, content with provenance provides indicators of authenticity so that consumers can have awareness of altered content. Such provenance could include what has been changed and the source of those changes. This ability to provide provenance for creators, publishers and consumers is essential to facilitating trust online.

To address this issue at scale for publishers, creators and consumers, the Coalition for Content Provenance and Authenticity (C2PA) has developed this technical specification for providing content provenance and authenticity. It is designed to enable global, opt-in, adoption of digital provenance techniques through the creation of a rich ecosystem of digital provenance enabled applications for a wide range of individuals and organizations while meeting appropriate security requirements. 

This specification has been, and continues to be, informed by scenarios, workflows and requirements gathered from industry experts and partner organizations, including the https://www.originproject.info/[Project Origin Alliance] and the https://contentauthenticity.org/[Content Authenticity Initiative (CAI)]. It is also possible that regulatory bodies and governmental agencies could utilize this specification to establish standards for digital provenance.

### Scope

This specification describes the technical aspects of the C2PA architecture; a model for storing and accessing cryptographically verifiable information whose trustworthiness can be assessed based on a defined xref:_trust_model[trust model]. Included in this document is information about how to create and process a C2PA Manifest and its components, including the use of digital signature technology for enabling tamper-evidence as well as establishing trust.

Prior to developing this specification, the C2PA created our https://c2pa.org/principles/[Guiding Principles] that enabled us to remain focused on ensuring that the specification can be used in ways that respect privacy and personal control of data with a critical eye toward potential abuse and misuse. For example, implementers of this specification are strongly encouraged to provide creators and publishers of media assets with the ability to control whether certain provenance data is included. 

[IMPORTANT]
====
From the overarching goals section of the guiding principles:

[quote]
C2PA specifications SHOULD NOT provide value judgments about whether a given set of provenance data is 'good' or 'bad,' merely whether the assertions included within can be validated as associated with the underlying asset, correctly formed, and free from tampering.
====

It is important that the specification does not negatively impact content accessibility for consumers.

Other documents from the C2PA will address specific implementation considerations such as expected user experiences and details of our threat and harms modelling.

// bring in the technical overview
// it is shared with the ISO version, so split it out here...
include::Overview.adoc[]


## Glossary

include::Glossary.adoc[]

## Normative References

include::NormRefs.adoc[]

## Standard Terms

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described in https://tools.ietf.org/html/bcp14[BCP 14], https://tools.ietf.org/html/rfc2119[RFC 2119], and https://tools.ietf.org/html/rfc8174[RFC 8174] when they appear in any casing (upper, lower or mixed).

CDDL Rules and Type Definitions in the CDDL schemas for C2PA constructs are normative. xref:schema-validation[Schema validation] is not necessary, nor it is recommended. Comments within CDDL schemas are non-normative. 

## Versioning

// the versioning doc is shared with ISO
// but not the history section
include::../Architecture/Versioning.adoc[]

include::Version_History.adoc[]
