== Terms and definitions

[[actor-definition]]
=== actor
human or non-human (hardware or software) that is participating in the C2PA ecosystem. For example: a camera (capture device), image editing software, cloud service or the person using such tools

NOTE: An organization or group of {{actor}}s may also be considered an {{actor}} in the C2PA ecosystem.

[[claim-generator-definition]]
=== claim generator
non-human (hardware or software) {{actor}} that generates the {{claim}} about an {{asset}} as well as the {{claim signature}}, thus leading to the {{asset}}'s associated {{C2PA Manifest}}

[[signer-definition]]
=== signer
credential holder of a private key that is used to sign the {{claim}}.  The {{signer}} is identified by the subject of the credential

=== manifest consumer
{{actor}} who consumes an {{asset}} with an associated {{C2PA Manifest}} for the purpose of obtaining the {{provenance data}} from the {{C2PA Manifest}}

=== validator
{{manifest consumer}} that performs {{C2PA Manifest}} validation

=== action
operation performed by an {{actor}} on an {{asset}}. For example, "create", "embed", or "apply filter"

=== digital content
portion of an {{asset}} that represents the actual content, such as the pixels of an image, along with any additional technical metadata required to understand the content (e.g., a colour profile or encoding parameters)

=== asset metadata
Non-technical information about the {{asset}} and its {{digital content}}

=== asset
file or stream of data containing {{digital content}}, {{asset metadata}} and optionally, a {{C2PA Manifest}}

NOTE: For the purposes of this definition, we will extend the typical definition of "file" to include cloud-native and dynamically generated data.

=== derived asset
{{asset}} that is created by starting from an existing {{asset}} and performing {{action}}s to it that modify its {{digital content}}

[example] 
**EXAMPLE:** An audio stream that has been shortened or a document where pages have been added.

=== asset rendition
representation of an {{asset}} (either as a part of an {{asset}} or a completely new {{asset}}) where the {{digital content}} has had a 'non-editorial transformation' {{action}} (e.g., re-encoding or scaling) applied

[example] 
**EXAMPLE:** A video file that is re-encoded for reduced screen resolution or network bandwidth.

=== composed asset
{{asset}} that is created by building up a collection of multiple parts or fragments of {{digital content}} (referred to as ingredients) from one or more other {{asset}}s. When starting from an existing {{asset}}, it is a special case of a {{derived asset}} - however a {{composed asset}} can also be one that starts from a "blank slate"

[example] 
====
**EXAMPLES:** 

- A video created by importing existing video clips and audio segments into a "blank slate". 
- An image where another image is imported and super-imposed on top of the starting image.
==== 

[[editorial-transformation-definition]]
=== editorial transformation
type of transformation that alters either the intent or meaning or both of the {{digital content}}.

[[assertion-definition]]
=== assertion
data structure which represents a statement either made (or "created") by the {{signer}} or simply gathered at claim generation-time, concerning the {{asset}}. This data is a part of the {{C2PA Manifest}}

[[claim-definition]]
=== claim
digitally signed and tamper-evident data structure that references a set of {{assertion}}s, concerning an {{asset}}, and the information necessary to represent the {{content binding}}. If any {{assertion}}s were redacted, then a declaration to that effect is included. This data is a part of the {{C2PA Manifest}}

[[claim-signature-definition]]
=== claim signature
digital signature on the {{claim}} using the private key of a {{signer}}. The {{claim signature}} is a part of the {{C2PA Manifest}}

[[c2pa-manifest-definition]]
=== C2PA Manifest
set of information about the _provenance_ of an {{asset}} based on the combination of one or more {{assertion}}s (including {{content binding}}s), a single {{claim}}, and a {{claim signature}}. A {{C2PA Manifest}} is part of a {{C2PA Manifest Store}}

NOTE: A {{C2PA Manifest}} can reference other {{C2PA Manifest}}s.

=== C2PA Manifest Store
collection of {{C2PA Manifest}}s that can either be embedded into an {{asset}} or be external to its {{asset}}

=== Content Credential
preferred, non-technical, term for a {{C2PA Manifest}}.  The {{C2PA Manifest Store}} therefore represents the Content Credentials of an asset

NOTE: Content Credentials also refers to the overall C2PA technology, and is therefore essentially treated as a plural noun. If a {{C2PA Manifest}} is a Content Credential, then multiple {{C2PA Manifest}} or the broader, universal concept is Content Credentials 

=== active manifest
last manifest in the list of {{C2PA Manifest}}s inside of a {{C2PA Manifest Store}} which is the one with the set of {{content binding}}s that are able to be validated

=== provenance
logical concept of understanding the history of an {{asset}} and its interaction with {{actor}}s and other {{asset}}s, as represented by the {{provenance data}}

=== provenance data
set of {{C2PA Manifest}}s for an {{asset}} and, in the case of a {{composed asset}}, its ingredients

NOTE: A {{C2PA Manifest}} can reference other {{C2PA Manifest}}s

=== authenticity
property of {{digital content}} comprising a set of facts (such as the {{provenance data}} and {{hard binding}}s) that can be cryptographically verified as not having been tampered with

=== content binding
Information that associates {{digital content}} to a specific {{C2PA Manifest}} associated with a specific {{asset}}, either as a {{hard binding}} or a {{soft binding}}

=== hard binding
One or more cryptographic hashes that uniquely identifies either the entire {{asset}} or a portion thereof

=== soft binding
content identifier that is either (a) not statistically unique, such as a {{fingerprint}}, or (b) embedded as an {{invisible watermark}} in the identified {{digital content}}

=== trust signals
collection of information that can inform a {{manifest consumer}}'s judgment of the trustworthiness of an {{asset}}. These are in addition to the {{signer}} upon which the fundamental trust model relies

=== C2PA Trust List
C2PA-managed list of X.509 certificate trust anchors that issue certificates to hardware and software {{signer}}s that are trusted to sign {{claim}}s


=== fingerprint
set of inherent properties computable from {{digital content}} that identifies the content or near duplicates of it

[example]
====
**EXAMPLE:** 
An {{asset}} becomes separated from its {{C2PA Manifest}} due to removal or corruption of {{asset}} metadata. A {{fingerprint}} of the {{digital content}} of the {{asset}} is used to search a database to recover the {{asset}} with an intact {{C2PA Manifest}}
====

=== invisible watermark
Information incorporated in a substantially human imperceptible way into the {{digital content}} of an {{asset}} which can be used, for example, to uniquely identify the {{asset}} or to store a reference to a {{C2PA Manifest}}

=== visible watermark
perceptible component of the {{digital content}} carrying some human consumable information about the provenance of the {{asset}}

=== manifest repository
repository into which {{C2PA Manifest}}s and {{C2PA Manifest Store}}s can be placed, and which can be searched using a {{content binding}}

=== durable Content Credential
a {{Content Credential}} for which there exists one or more {{soft binding}}s that enable its discovery in a {{manifest repository}}.
